version: '3'
services:
  db: 
    image: mongo:3.4

  backend:  # Remova o espaço em branco antes de "backend"
    image: node:14
    volumes:
      - ./backend:/backend
      - /backend/node_modules
    ports:
      - "3000:3000"
    command: bash -c "cd /backend && npm install && node app.js"

  frontend: 
    image: nginx:1.13
    volumes:
      - ./frontend:/usr/share/nginx/html/
    ports:
      - "80:80"
